Tests & Enum
Tutritp01/TgBot pull request #1
Opened 2022-07-03 22:33 UTC by Sav4ykVladzislau

https://schneidervs.atlassian.net/browse/TGBOT-2

2022-07-04 17:46 UTC, max-java requested changes
ptal

2022-07-04 17:46 UTC, max-java commented on tg-bot/src/main/java/com/tutrit/tgbot/example/service/TelegramBot.java
> +@PropertySource("application.properties")
That is not necessary, cose that is a default value

2022-07-04 17:46 UTC, max-java commented on tg-bot/src/test/java/com/tutrit/tgbot/example/config/Mapper.java
> +package com.tutrit.tgbot.example.config;
class could be deleted, the one from `src` should be used

2022-07-04 17:46 UTC, max-java commented on tg-bot/src/test/java/com/tutrit/tgbot/example/service/StatusServiceTest.java
> +        StatusService.choice(OrderStatus.REQUEST);
and?

2022-07-04 17:46 UTC, max-java commented on tg-bot/src/test/java/com/tutrit/tgbot/example/service/TelegramBotTest.java
> +}
add empty row

2022-07-11 09:08 UTC, schneidervs commented
передалай, плиз

2022-08-07 12:39 UTC, max-java commented
outdated

2022-08-07 12:39 UTC, closed without merging