Tgbot 44 - Create object provider for Customer objects
Tutritp01/TgBot pull request #22
Opened 2022-08-08 19:11 UTC by yurasava

https://schneidervs.atlassian.net/browse/TGBOT-44
Created a CustomerProvider class that exposes 5 customer objects.
There are also tests for the methods of the CustomerProvider class.

2022-08-09 20:25 UTC, schneidervs approved these changes

2022-08-11 09:18 UTC, Sav4ykVladzislau submitted a review, later dismissed
Lgfm

2022-08-11 14:25 UTC, yurasava commented on stoservice/src/main/java/com/tutrit/stoservice/provider/CustomerProvider.java
> +            result.add(new Customer(initial.getId().concat(String.valueOf(i)),
This is the same

2022-08-11 14:43 UTC, schneidervs commented on stoservice/src/main/java/com/tutrit/stoservice/provider/CustomerProvider.java
> +            result.add(new Customer(initial.getId().concat(String.valueOf(i)),
sorry.  this is my bad english.  I mean it's possible.

2022-08-13 22:46 UTC, AlexanderYarokhovich approved these changes
good

2022-08-14 11:30 UTC, max-java requested changes
please simplify provider logic

2022-08-16 17:07 UTC, schneidervs commented
LGFM

2022-08-16 17:07 UTC, schneidervs approved these changes

2022-08-16 17:22 UTC, Sav4ykVladzislau approved these changes
lgfm

2022-08-16 17:41 UTC, lamaconda approved these changes
lgfm

2022-08-16 17:56 UTC, merged